; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	I:\test_git\Lab_1_1\Visual_Studio_2010_environment\1_1\Source_code\sort.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?sort@@YAXQAHH@Z				; sort
EXTRN	_mergeSort:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File i:\test_git\lab_1_1\visual_studio_2010_environment\1_1\source_code\sort.cpp
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT ?sort@@YAXQAHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_size$ = 12						; size = 4
?sort@@YAXQAHH@Z PROC					; sort, COMDAT
; Line 10
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 11
	mov	eax, DWORD PTR _size$[ebp]
	sub	eax, 1
	push	eax
	push	0
	mov	ecx, DWORD PTR _a$[ebp]
	push	ecx
	call	_mergeSort
	add	esp, 12					; 0000000cH
; Line 13
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?sort@@YAXQAHH@Z ENDP					; sort
_TEXT	ENDS
END
